install:
	mkdir -p "$${HOME}/.config/micro/plug/micro-autofmt/help"
	cp autofmt.lua "$${HOME}/.config/micro/plug/micro-autofmt/autofmt.lua"
	cp repo.json "$${HOME}/.config/micro/plug/micro-autofmt/repo.json"
	cp settings.json "$${HOME}/.config/micro/settings.json"
	cp help/autofmt.md "$${HOME}/.config/micro/plug/micro-autofmt/help/autofmt.md"
	cp .clang-format "$${HOME}/.clang-format"
